### ISSUE TITLE
Script has reached daily maximum run time of 90 minutes. Script must pause for 24 hours to reset Google Quotas, and will resume at that time. For more information, please see https://developers.google.com/apps-script/guides/services/quotas

### ISSUE THREAD

**Issue by zozev** [ericyd/gdrive-copy#100]
Hello, I have a few thousands file, after 2000~ files got this - Script has reached daily maximum run time of 90 minutes. Script must pause for 24 hours to reset Google Quotas, and will resume at that time. For more information, please see https://developers.google.com/apps-script/guides/services/quotas
Any way add another google account for avoid this quotas? or use my own account

**Comment by ericyd** [comment]
Not at this time, no. There is an open request to add a feature like this (#72).
