### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by vaccarieli** [ericyd/gdrive-copy#106]
when I try to push files to my Gdrive this is the error that I get, I`ve been searching for a soltution but no luck at all, what could be the issue ? 
<--- Last few GCs --->

[1236:000002369E958B20]   256376 ms: Mark-sweep 1223.5 (1244.7) -> 1223.5 (1241.7) MB, 102.6 / 0.0 ms  last resort GC in old space requested
[1236:000002369E958B20]   256469 ms: Mark-sweep 1223.5 (1241.7) -> 1223.5 (1241.7) MB, 92.8 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000015DFF4A5891 <JSObject>
    2: replace(this=000003EC2AE21F89 <Very long string[170759512]>,0000030EA1A843A9 <JSRegExp <String[19]: [\x00-\x1f\x27\x5c]>>,0000030EA1A844A9 <JSFunction escapeFn (sfi = 0000015DFF4C5499)>)
    3: strEscape(aka strEscape) [util.js:111] [bytecode=0000012DFFD51019 offset=89](this=0000039A22E822D1 <undefined>,str=000003EC2AE21F89 <Very long string[170759512]>)
    4: formatPrimitive(aka forma...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewFixedArrayWithHoles
 5: v8::internal::interpreter::BytecodeArrayRandomIterator::UpdateOffsetFromIndex
 6: v8::internal::interpreter::BytecodeArrayRandomIterator::UpdateOffsetFromIndex
 7: 000003D10B8843C1

**Comment by koshtaayush** [comment]
I am stuck with the same issue. How did this get solved ?

**Comment by ericyd** [comment]
I have no idea, what are the steps to reproduce?
