### ISSUE TITLE
**REQUEST** ABILITY TO COMPARE FILES WITHIN A FOLDER AND COPY MISSING ONES

### ISSUE THREAD

**Issue by vaccarieli** [ericyd/gdrive-copy#107]
Is there a way you could implement a feature to once you copy a folder, if the folder itself gets updates recheck to find whats the difference and copy new files ?

That will be helpfull.

**Comment by ericyd** [comment]
No I cannot implement this, it would require a service running continuously to monitor for changes. It is substantially outside the scope of this project
