### ISSUE TITLE
Finding Folder never finds the folder

### ISSUE THREAD

**Issue by lucienorrin** [ericyd/gdrive-copy#11]
When pasting the 'shared with me' folder link into the paste folder box sometimes it does not find the folder and just continues to spin. So far it has only happened with folders that have a substantial amount of data in them.
The alternative Select Folder option shows every folder in the drive which can be in the hundreds or thousands if the drive account is substantial. 
Overall awesome project though. I have been searching for something like this for a while now. Thank you for creating it.

**Comment by ericyd** [comment]
There might be an issue with the way it is pulling in the metadata for the folder.
Do the problem folders have multiple parent folders? Are they shared in a Team Drive?

**Comment by ericyd** [comment]
The interface has been totally revamped. Will re-open if this is reported again.
