### ISSUE TITLE
 API call to drive.files.copy failed with error

### ISSUE THREAD

**Issue by OgnistyPoland** [ericyd/gdrive-copy#111]
### Are you requesting a feature or reporting a bug?
Bug
### If reporting a bug, is there already an issue open for this same bug?
I think yes
### My problem:
Error:  API call to drive.files.copy failed with error: User rate limit exceeded. File: GDriveService (Copy Folder). Line: 93

https://i.imgur.com/TKR0TOL.png
### Specify your

* operating system: Windows 10
* browser: Chrome

**Comment by ericyd** [comment]
duplicate of #86
