### ISSUE TITLE
Can I use my own paid g-suite account if I deploy app for myself to avoid 90 min limit??

### ISSUE THREAD

**Issue by newbieh4cker** [ericyd/gdrive-copy#117]
#72 
#100 
#115 

To avoid 90 min limits,
Can I use my g-suite account if I deploy app for myself?? (to avoid certain limits)

**Comment by ericyd** [comment]
Yes, you can do that. You'll just need to change this constant accordingly

https://github.com/ericyd/gdrive-copy/blob/master/lib/Timer.ts#L11

I guess I need to do some issue clean up :joy:
