### ISSUE TITLE
[BUG] ReferenceError: "Logging" is not defined.

### ISSUE THREAD

**Issue by newbieh4cker** [ericyd/gdrive-copy#119]
### Are you requesting a feature or reporting a bug?
reporting bug

### If reporting a bug, is there already an issue open for this same bug?
no

### What is the current behavior?
"Logging" is not defined.

### What is the expected behavior?
"Logging" is defined, and logging is working

### Specify your

* operating system: macOS
* browser: Chrome

I'm using my own deploy version to use paid g-suite account.
I've deploy it to web app, and If i go to 'G Suite Developer Hub'
G Copy shows error

![image](https://user-images.githubusercontent.com/23703741/63733919-3415f200-c8b5-11e9-822b-5ccd7343bb3a.png)

**Comment by newbieh4cker** [comment]
Okay, I found something strange.
in 'main.ts' from command line, Logging was defined.
![image](https://user-images.githubusercontent.com/23703741/63734066-c6b69100-c8b5-11e9-891f-2b7290cc962a.png)


But in 'main.gs' from script.google.com/~~~/edit, definition og Logging is being commented. 
![image](https://user-images.githubusercontent.com/23703741/63734114-ec439a80-c8b5-11e9-888e-ebae03be06b6.png)

**Comment by newbieh4cker** [comment]
it seems like somehow "~/dist/util' folder is not included while deploy.
I can see 'Logging.ts' in ~dist/util folder
But, In G suite Developer Hub, there is not Logging.gs
![image](https://user-images.githubusercontent.com/23703741/63734833-c5d32e80-c8b8-11e9-92b0-a8830ff6ed5c.png)

**Comment by newbieh4cker** [comment]
git reset 0d4d926e887482324262047e2c0f0708be43caf2
npm run build:prod
clasp push
clasp deploy

with that,
 - yes, "ReferenceError" is fixed,
 - but, as you can see from below screenshot, "list of fils and folders" are not updating, even actually it copied 10 files and progress is complete
![image](https://user-images.githubusercontent.com/23703741/63816630-e4e2c680-c973-11e9-91b8-bf78ee749414.png)

**Comment by ericyd** [comment]
This should be fixed. Please `git pull` to fetch the latest master branch and try again.

I also renamed the Timer constants referenced in #120 to be a little more specific and clear.
