### ISSUE TITLE
Not showing any available folders in Gdrive

### ISSUE THREAD

**Issue by wellandgoodsam** [ericyd/gdrive-copy#12]
Hello,

Recently when I select "Copy Folder" it does not show any available files to copy from Gdrive. It does show me as logged in through my gmail account. "Logged in as sam@XXXXX"

![screen shot 2017-03-23 at 11 52 23 am](https://cloud.githubusercontent.com/assets/26630042/24256722/4c7001b2-0fbf-11e7-855b-d1c1152ad9f2.png)

Please advise.

Thanks

**Comment by ericyd** [comment]
I'm not able to reproduce this issue.
Could you confirm if the issue is persisting and which browser and OS you are using?

**Comment by ericyd** [comment]
I believe this is the same issue reported in #13, and I am convinced this was an issue on Google's end.

**Comment by wellandgoodsam** [comment]
@ericyd Thanks. Not sure what the issue was, but it seems to have self-corrected. (We were using Chrome). I agree probably an issue on Google's end. Thanks again for the great tool!
