### ISSUE TITLE
[Question] about runtime limits

### ISSUE THREAD

**Issue by newbieh4cker** [ericyd/gdrive-copy#120]
### Are you requesting a feature or reporting a bug?
question

your source code
![image](https://user-images.githubusercontent.com/23703741/63901833-4755c880-ca41-11e9-8c61-137ce52ad551.png)

google policy - quota
![image](https://user-images.githubusercontent.com/23703741/63901845-563c7b00-ca41-11e9-84bf-30dad975da5d.png)

google policy - limitation
![image](https://user-images.githubusercontent.com/23703741/63901861-648a9700-ca41-11e9-98ee-c8ae73d034f1.png)

Q1. Your code's 'Timer.MAX_RUNTIME_PER_DAY' is for Google's 'Triggers total runtime'.
If I'm using g suite business account, I can change it to 355 (about 6 hours). right?

Q2. Your code's 'Timer.MAX_RUNTIME' is for Google's 'Script runtime'
If I'm using g suite business account, I can change it to 28  (about 30 minutes). right?

Q3. Your code has 'Timer.oneDay', and 'Timer.sixMinutes' variables. What are those for??

**Comment by ericyd** [comment]
Q1: Correct, changing it to `(355 * 1000)` will allow it to run for 355 minutes per day. Values are in milliseconds

Q2: Correct, changing it to `(28 * 1000)` will allow it to run for 28 minutes at a time.

Q3: The values should really be declared as constants not just variables but oh well. Those are the "sleep" times used to set triggers for the script to resume. The way the script works, it will set the trigger _before_ the script runs. The `oneDay` value should stay the same, but the `sixMinutes` value should be updated (and probably renamed but that's a separate issue). I'd recommend something like this

```
# set the sleep time to 1.5 minutes longer than the runtime. This will make the script sleep for 1.5 minutes between each execution.
Timer.sixMinutes = Timer.MAX_RUNTIME + (1.5 * 1000 * 60)
```
