### ISSUE TITLE
Search Not Working

### ISSUE THREAD

**Issue by djlexluthar** [ericyd/gdrive-copy#121]
In the 'Select a Folder' window, the search function is no longer working. It used to display all folders named with the search term, but now it's just blank (see attached screenshot). And yes, I've triple verified that I have an appropriately named folder in my Google Drive.

It will still display all folders when I open the 'Select a Folder' window, but scrolling through every folder in my drive to find the one I'm looking for is nearly impossible.

Copying and pasting the Google Drive folder URL still works just fine; it just takes a few more minutes to open Google Drive, navigate to the folder, copy the URL and paste it.

OS: Windows 10
I've reproduced the issue on Chrome (including in Incognito Mode) and on Firefox

![Copy a Folder](https://user-images.githubusercontent.com/3342881/63939241-0307ff80-ca24-11e9-9f81-58e0419229c3.png)

**Comment by ericyd** [comment]
I'm sorry to say this is just a plugin provided by Google Apps Script and I really don't have any control over how well the search is working. No changes have been made to this portion of my script in ages so I'm hopeful that Google will resolve the issue soon.
