### ISSUE TITLE
Error:  API call to drive.files.copy failed with error: File not found: . File: GDriveService (Copy Folder). Line: 93

### ISSUE THREAD

**Issue by iamvpk** [ericyd/gdrive-copy#122]
### Are you requesting a feature or reporting a bug?
Bug
### If reporting a bug, is there already an issue open for this same bug?
No
### What is the current behavior?
Error:  API call to drive.files.copy failed with error: File not found: . File: GDriveService (Copy Folder). Line: 93
### Specify your

* operating system: Windows 10 Pro x64 Latest Build
* browser: Google Chrome

**Comment by ericyd** [comment]
Duplicate of #54
