### ISSUE TITLE
Team Drive Support

### ISSUE THREAD

**Issue by 420tushar** [ericyd/gdrive-copy#124]
### Are you requesting a feature or reporting a bug?
Requesting a Feature ( Actually want to know if it exists)

 As I Found in previous issues someone  asked for Team Drive Compatibility is It Done or You haven't added Team Drive Compatibility Yet ? Cause There is a Stale Branch Names Team Drive. Pardon My English :( 
* operating system:  Windows 10
* browser: Chrome Latest Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by ericyd** [comment]
No it is not done. I will close the other issue when/if complete
