### ISSUE TITLE
I could not find any folders in this script

### ISSUE THREAD

**Issue by zdptrsz** [ericyd/gdrive-copy#13]
I cannot find any folders.Something wrong with this script.Please fix this script.Thanks very much!

**Comment by ericyd** [comment]
Unfortunately this description gives me no information to assist or understand the issue.  Please provide more details.

**Comment by zdptrsz** [comment]
This Problem did not exist any more!.Maybe Google company temporarily adjusted some of the interface code, and then restored.Thanks very much

**Comment by ericyd** [comment]
Glad it's resolved.  This same issue was reported by a few other users directly to my email and they confirmed that it was resolved.  Must have been a minor bug and subsequent bug fix on Google's end.
