### ISSUE TITLE
Deleted folders still appeared in "search your drive"

### ISSUE THREAD

**Issue by vdmcorpulent** [ericyd/gdrive-copy#130]
### Are you requesting a feature or reporting a bug?
bug
### If reporting a bug, is there already an issue open for this same bug?
i dont know
### What is the current behavior?
after deleting many folders on root, those folders still appeared when i tried to copy after clicking "search your drive"
### What is the expected behavior?
normally, all deleted folders will not appear on the search ("search your drive")
### How would you reproduce the current behavior (if this is a bug)?
the chronology of the problem:
1. i was processing some folder to be copied and pasted on root
2. during the process I accidentally deleted the recently all pasted folders . the copying process is not yet completed
3. then I delete everything, included the origin (the files that i want to copy).
4. now, every folders that i delete appear on "search your drive"
### Specify your
windows 10, chrome
* operating system:
* browser:

**Comment by ericyd** [comment]
This doesn't sound like a bug. The search feature uses a Google widget called Picker which searches your Drive. Unless you moved items to the trash and then went to Trash and selected Permanently Delete, I would expect deleted items to remain in search. This is a function of Google Drive, not of this app.
