### ISSUE TITLE
Copy process too slow - how to permanently stop?

### ISSUE THREAD

**Issue by DZNX** [ericyd/gdrive-copy#133]
Hello all,

I've been using this excellent app to copy approximately 1400 folders containing 6800 files. The permissions need to remain intact so I ticked that box. The copy process is so slow that it's been at it for 4 days (ie, 4x 90 minute sessions) and only copied 1124 files. Unfortunately, this is within a work environment and I need to have ALL the folders and files copied by the end of today. Clearly this is not going to happen and a decision has been made to abandon the copying process.

Question: As the copying process restarts automatically every 24 hours, how do I permanently stop the process? Is it as simple as hitting pause and then deleting the app?

I'm grateful for any and all information you can share.

Thank you.

Dan

**Comment by ericyd** [comment]
Yep just press the Pause button in the app. After you get a success message, you should see the copy log pause momentarily. 

Deleting the app just amounts to removing permissions, which you are free to do at any time.
