### ISSUE TITLE
User rate limit exceeded. File: GDriveService (Copy Folder). Line: 93

### ISSUE THREAD

**Issue by daeeun** [ericyd/gdrive-copy#134]
### Are you requesting a feature or reporting a bug?
bug

### If reporting a bug, is there already an issue open for this same bug?
yes

### What is the current behavior?
After copying about 8,000 items, the "Paused due to Google quota limits - copy will resume in 1-2 minutes" message appeared 4 times, then " User rate limit exceeded. File: GDriveService (Copy Folder). Line: 93" apppears over and over again.
If a pause then resume copying, it starts to copy about 10 files (that was previously copied), then the same "User rate limit exceeded" message appears again.

### What is the expected behavior?
keep copying

### How would you reproduce the current behavior (if this is a bug)?
pause and resume copying

### Specify your

* operating system: macOS Catalina
* browser: Chrome

**Comment by ericyd** [comment]
I don't have time to work on this project, I'm consolidating all the "user rate limit exceeded" errors into #82 which is the oldest open bug for this error. I will gladly review any PRs to resolve this issue.
