### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SripriyaMohan** [ericyd/gdrive-copy#135]
Copy Folder is not copying all items in the folder. Tried on different browsers, different devices, for the last 3 months -- there's always an error and the copy is incomplete. My team has also reported bugs previously about this. Please support. Thanks.

**Comment by ericyd** [comment]
what is the error message?

**Comment by SripriyaMohan** [comment]
Hi Eric,

The sub-folders within the main folder do not copy fully -- and there's
always an incomplete copy log that just hangs and stops mid-way. Not sure
why this happens, have tried with different browsers as well.

Looping my colleague Jessica to share more info on this issue.

Thanks,
Priya
