### ISSUE TITLE
Request for sync update folder option

### ISSUE THREAD

**Issue by trexhunter7** [ericyd/gdrive-copy#141]
issue : no update folder option available
req : an option to update a already make folder  .
example : folder "Z" is shared with me on drive , i use the tool and make a copy in my root drive , however now after 10 days contents of folder Z are updated , now one should be able to update the corresponding folder in my drive too.

**Comment by 3xploiton3** [comment]
Yeah very useful feature, and add option for merge or duplicate file

**Comment by ericyd** [comment]
This isn't going to be added, its really not designed to be an app that indefinitely polls your folders for changes. It also doesn't work well when user's copy multiple folders concurrently so I could see issues with trying to monitor multiple folders. Also, just no time to implement, and no one else contributes to this project.
