### ISSUE TITLE
How can I get more time? It´s only working 90 min per day 

### ISSUE THREAD

**Issue by Gabbdr** [ericyd/gdrive-copy#144]
### Are you requesting a feature or reporting a bug?
Requesting a feature
### Specify your

* operating system:
* browser: Google Chrome

**Comment by ericyd** [comment]
This is discussed in #120 and #139

**Comment by Dhanamerdeka** [comment]
This feature not yet present?

**Comment by ericyd** [comment]
I'm not adding a feature for this, the recommendation is to deploy your own version with updated timer values. See linked issues
