### ISSUE TITLE
What happens if I turn off PC?

### ISSUE THREAD

**Issue by 1234gsdfgbs** [ericyd/gdrive-copy#152]
I just want to know... 
I get this message, but I don't want to leave my PC on 24/7.
"Script has reached daily maximum run time of 90 minutes. Script must pause for 24 hours to reset Google Quotas, and will resume at that time. For more information, please see https://developers.google.com/apps-script/guides/services/quotas"

What happens if I turn off PC? Does is store the progress? How do I resume the transfer later?

**Comment by ericyd** [comment]
You can turn off your computer at any time, it's running on a server so your computer has no effect on the script after you initiate it
