### ISSUE TITLE
Copy stopped at 460th file

### ISSUE THREAD

**Issue by berserker465** [ericyd/gdrive-copy#16]
Hello
I've been trying to copy 2 folders recently, each one having over 1000 files, I tried to copy both folders separately, but for both of them it only copied exactly 460 files, not one more.

I double checked both folders to be sure and they both have above 1500 files each.

The copy folder log reports operation as "Complete" and no errors are reported.

**Comment by berserker465** [comment]
Tried again after a few days and it still stops at 460th file, seems like this isn't related to the other day's bug which stopped many google scripts the other day.

**Comment by ericyd** [comment]
I have never been able to reproduce this behavior or had it reported by anyone else. I'm going to close this for now but please feel free to comment with more details if it occurs again.
