### ISSUE TITLE
Bug: Insufficient Permissions

### ISSUE THREAD

**Issue by aeparson** [ericyd/gdrive-copy#161]
**BUG**

I wan unable to find anything else referencing this bug.

I am trying copy all of the files from my work drive before I leave the organization on June 23. I have followed all of the directions in the FAQ about transferring between organizations, but with recent sharing updates in Drive you can no longer add the folder to your own drive. It now only adds a "shortcut to the folder."

I get the following error every time I try to copy it over: 
**API call to drive.files.insert failed with error: Insufficient permissions for the specified parent.**

I am using Chrome Version 83.0.4103.97 on a MAC running MacOS Catalina Version 10.15.3.

Thanks for any help you can give,
Arcadia

**Comment by ericyd** [comment]
Ultimately this is the same root cause as #5 so I'm going to close as a dupe.

Solution: select "Root of My Drive" in the copy destination, instead of "Same as source". Or, you could select a custom copy destination if preferred.

Ideally, the app would be smart enough to default to Root when "Same as source" throws an error, but I don't anticipate ever adding this functionality so this workaround will have to suffice.

**Comment by aeparson** [comment]
I was actually using a custom destination because I’m trying to copy it
from my work domain to a personal drive. I’m sorry I didn’t make that
clear.

**Comment by ericyd** [comment]
Hm, yeah that appears to be another bug.

Ok, amendment to my above solution: Just use the "Root of My Drive" option, and then move the folder manually once it's moved.

Sorry for the hassle.

**Comment by aeparson** [comment]
Because Google is no longer adding the actual folder to your drive, only a
“shortcut,” this doesn’t seem to be working. I go to my personal account
where it is shared to. I added the shortcut since that’s my only option. It
can’t find the folder either with the share link or with the url when I’m
in the folder.

The only place I can get the link to work from is the original work account
drive. But copying it to the root will just make another copy in my work
drive, not give me a copy in my personal drive.

Any other ideas?

**Comment by ericyd** [comment]
I just used the "Root of My Drive" option with a folder from another domain with the "shortcut" option right before I commented here, I am positive it worked (at least on my machine 😂). 

Unfortunately there are no other options, but the steps I took were

1. From domain B, share folder
2. From domain A, select "Add Shortcut to Drive" from the folder in the "Shared with Me" section
3. Click into the folder with domain A and copy folder URL
4. Navigate to app (bit.ly/cpfolder) and paste the folder URL
5. Select "Root of My Drive" on the parent folder selection view

That worked for me, if the same steps aren't working for you unfortunately I don't have any recommendations.

**Comment by aeparson** [comment]
It worked! I wonder if it wouldn’t work before because I was in a Google
Window signed in on my work account. This time I tried in the window signed
into the personal one.

Either way, thank you so much for your help. This app is a lifesaver for a
ton of people. You rock!
