### ISSUE TITLE
A question about how it works, and a thanks.

### ISSUE THREAD

**Issue by theheartbenvn** [ericyd/gdrive-copy#169]
I'm a bit of a slowpoke, but i was wondering how does this app work, specifically about moving contents between one domain to another? Does it like temporary downloading the files onto your machine and put it onto the other drive? Or does it like execute a bunch of commands to make Google work and put those files onto the other drive?

And by the way, i'd like to send my thanks to you. You saved my buns with this. I wish i could send a few bucks to you, but my payment options are limited. ( i'm still under parental guardians' management so i can't really pay anything that's virtual and outside of my country. )

**Comment by ericyd** [comment]
No worries, I'm not accepting payment anymore for this app now that I'm not maintaining it anymore.

The short version is it uses [Google Apps Script](https://developers.google.com/apps-script) to host and execute the essential processes. It uses [Triggers](https://developers.google.com/apps-script/guides/triggers) to schedule the job, and the [Drive API](https://developers.google.com/drive/api/v2/reference/files/list) to [list files](https://developers.google.com/drive/api/v3/reference/files/list) in the folder and recursively [copy them](https://developers.google.com/drive/api/v2/reference/files/copy).

It's not a very well-structured app but it essentially is one large script that runs from the [main function](https://github.com/ericyd/gdrive-copy/blob/0b6f9464d40bd96664fe417af9deffb1f2b13d72/lib/main.ts). It saves data in the user's own Google Drive in a JSON file to keep track of it's own progress, and also uses Google Apps Script's [Properties store](https://developers.google.com/apps-script/reference/properties/properties-service), which is limited to a specific user's account, for some additional metadata.
