### ISSUE TITLE
Submitted URL Undefined

### ISSUE THREAD

**Issue by connermurphy** [ericyd/gdrive-copy#174]
![image](https://user-images.githubusercontent.com/11260194/96701572-ab93c400-1388-11eb-8e76-eace920e55d5.png)
Any idea why this would be happening? Or has anyone had this issue and it's been solved. Can't seem to find an existing issue anywhere.

**Comment by ericyd** [comment]
It says you submitted `undefined`. Are you pasting a URL where you're supposed to paste a URL?

**Comment by connermurphy** [comment]
Turns out DriveAPI had somehow disabled itself. Problem was solved by just re-enabling it...
