### ISSUE TITLE
[suggest] add verify feature + quota setting

### ISSUE THREAD

**Issue by Dhanamerdeka** [ericyd/gdrive-copy#178]
Hello dev
umm.. i think this script need a verify feature...
because at copying a lot of software and data... this script mostly get error at copying file
like... at some case... some folder or files not copied
so yeah....
i think it will be better to make a system where the script doublecheck two times on the end of it

and yeah i think it's good too to adding feature like quota settings.... like... gsuite and another
like... dropdown quota setting manual... if the automatically doesn't possible

**Comment by ericyd** [comment]
this is not a good issue. In fact, it's not even an issue, it's more just your thoughts on the product, which isn't the purpose of GitHub issues.
