### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by Oshekher** [ericyd/gdrive-copy#180]
I have view right in many team drive but I am stil not able to copy their folders to my drive ( only able to copy my own folders ).
![Screenshot_20210115-233520](https://user-images.githubusercontent.com/67940483/104762444-61a15b00-578a-11eb-9629-39d19c36b085.png)

**Comment by Oshekher** [comment]
Outdated script

**Comment by greatvovan** [comment]
You are just doing it wrong. Share the folders from the source account, give all the permissions and move the folders to destination account. Now copy the URL in **destination** account and feed it to the script. As per today, the script is not outdated and does its work.
