### ISSUE TITLE
Broken...

### ISSUE THREAD

**Issue by 50Spence** [ericyd/gdrive-copy#20]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

Paste an URL and the Finding Folder Icon comes up and spins for days

### What is the expected behavior?

Usually, when I paste an URL the folder comes up really fast.

### Specify your

* operating system: Windows 10
* browser: Google Chrome

**Comment by ericyd** [comment]
Not able to reproduce. Can you try again? There has been some weird server behavior from Google recently and I'm wondering if this is related.

**Comment by ericyd** [comment]
Same report as #11

**Comment by ericyd** [comment]
The interface has been totally revamped. Will re-open if this is reported again.
