### ISSUE TITLE
Bug: White Screen upon selecting Copy Folder button

### ISSUE THREAD

**Issue by rcky711** [ericyd/gdrive-copy#21]
### Are you requesting a feature or reporting a bug?
=> Bug

### What is the current behavior?
=> Upon first use, receiving a white screen citing a URL like:
https://script.google.com/a/macros/vroozi.com/s/AKm7uyo/exec

The white screen does not go anywhere and I cannot find any result of the script actions.

### What is the expected behavior?
=> Selected folder is copied along with sub directories to the same directory as the source folder with the newly entered name

### How would you reproduce the current behavior (if this is a bug)?
=> Create shared directory with sub-directories; attempt to copy this shared directory without changing any of the default permission/location options

### Specify your

* operating system: Win 10 x64
* browser: latest Chrome

**Comment by ericyd** [comment]
This is the same bug report as #15 and #17

**Comment by ericyd** [comment]
The interface has been totally revamped. Will re-open if this is reported again.
