### ISSUE TITLE
Feature Request: Using Copy Folder App On View Only Access Folders

### ISSUE THREAD

**Issue by gie0513** [ericyd/gdrive-copy#27]
### Are you requesting a feature or reporting a bug?
Query: Is It Possible use your Copy Folder extension if I only have viewing access to a folder and its contents?

### What is the current behavior?
works fine if I have editing access or ownership of the folder

### What is the expected behavior?
That a copy of the folder and its contents to which I only have viewing access 

### How would you reproduce the current behavior (if this is a bug)?
N/A

### Specify your

* operating system: Windows OS10
* browser: Chrome

**Comment by ericyd** [comment]
This already works.  You might need to add the folder to your drive first.  If you have it available in the "Shared with me" section, you can add it to your drive by right-clicking and selecting "Add to My Drive".
