### ISSUE TITLE
Still copying sharing permissions despite being checked NO

### ISSUE THREAD

**Issue by CAJarrett** [ericyd/gdrive-copy#28]
### Are you requesting a feature or reporting a bug?

Reporting a bug

### What is the current behavior?

I follow the instructions, making sure "Copy Sharing Permissions" is set to No. I proceed. When I go look at the copy, all of the sharing permissions are still the same. The whole reason I wanted this app was so I could bulk copy and remove all the sharing permissions.

### What is the expected behavior?

That it would do as it has stated and NOT copy the sharing permissions when it is set to NO.

### How would you reproduce the current behavior (if this is a bug)?

I am not doing anything outside of following the on screen form prompts. 

### Specify your

* operating system: Windows 10 Home
* browser: Chrome

**Comment by ericyd** [comment]
I recently rewrote the front end interface and some of the details in the way the information is passed to the server. Could you try again and see if you can reproduce this behavior?
