### ISSUE TITLE
How do you stop the copy? PLEASE HELP!

### ISSUE THREAD

**Issue by TJoe36** [ericyd/gdrive-copy#3]
The script is stuck in a loop, making copies of the same documents over and over again. 

How do you stop script before it is done?

**Comment by ericyd** [comment]
Use the "pause" function in the app. It is in the main navigation bar at the top
Eric Dauenhauer
ericyd.com
eric@ericyd.com

---- On Tue, 01 Nov 2016 04:27:44 -0700 notifications@github.com wrote ----

The script is stuck in a loop, making copies of the same documents over and over again.

How do you stop script before it is done?

**Comment by ericyd** [comment]
I've reverted a recent update that was causing this, it shouldn't happen again.








---- On Tue, 01 Nov 2016 04:27:44 -0700TJoe36 &lt;notifications@github.com&gt; wrote ----




The script is stuck in a loop, making copies of the same documents over and over again.

How do you stop script before it is done?

**Comment by TJoe36** [comment]
Thank you.

I was able to access the pause screen.

Will someone be able to help me understand what the copy feature was stuck
in a continuous loop?

*~ t*

[image: Inline image 1]

**Comment by ericyd** [comment]
I've added some try/catch blocks to prevent the permissions error that was causing this loop.  If it occurs again for anyone, please add a comment and I'll investigate further.

**Comment by ThomasPonnet** [comment]
Hello,
I just tried the plugin for the first time. So far I have three copies of my second level folders (all under the same target folder) and copying still continues for the lower level ones.
I'd love to pause but the 'Pause' menu item is greyed out - clicking it doesn't give a response. Any suggestions welcome!

**Comment by ericyd** [comment]
Refresh the page and the link will become active.
Eric Dauenhauer
ericyd.com
eric@ericyd.com

---- On Tue, 29 Nov 2016 18:28:15 -0800 notifications@github.com wrote ----

Hello,
I just tried the plugin for the first time. So far I have three copies of my second level folders (all under the same target folder) and copying still continues for the lower level ones.
I'd love to pause but the 'Pause' menu item is greyed out - clicking it doesn't give a response. Any suggestions welcome!

**Comment by christinadeville** [comment]
mine is still looping and sending error messages and creating duplicate files even after I paused it, I need this to stop. please help

**Comment by ericyd** [comment]
I've removed a chunk of code that I believe was responsible for first introducing the infinite loop bug.
