### ISSUE TITLE
There was an error initializing the copy folder request.

### ISSUE THREAD

**Issue by dschroed** [ericyd/gdrive-copy#30]
### Are you requesting a feature or reporting a bug?
Error / Bug?

### What is the current behavior?
Error: There was an error initializing the copy folder request.
Error message: Exception: The feature you are attempting to use has been disabled by your domain administrator..
Please try again. Make sure you have correct permissions to copy this folder, and make sure you are using Google Chrome or Chromium when using this app.

### What is the expected behavior?
Copy a folder in the desition account

### How would you reproduce the current behavior (if this is a bug)?
1) add access to different domain user (G Suite) from standard google apps account.
2)
- use your tool from a Private Window from G Suite account (Destination Drive account)
- Parameter
Folder to copy.  XXX-ARCHIVE 
New Folder Name:  XXX-v2
Copy sharing permissions  NO
Copy folder to Root directory (i.e. at the top of "My Drive")

Note the file to be copied is in the MY Drive Folder (added already).
The App is started / initiated from the APP Window in Chrome not in the Drive feature. (could not add it here). If this is the case, what would be the admin minimum requirements for the G Suite Admin to be enabled?! Less secure apps are currently enabled for all users!

### Specify your

* operating system: Win 7 Prof As well OSx recent updates installed
* browser: Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by ericyd** [comment]
Did you "Add to Chrome" and then access it that way? Or did you go directly to the website link, https://script.google.com/macros/s/AKfycbxbGNGajrxv-HbX2sVY2OTu7yj9VvxlOMOeQblZFuq7rYm7uyo/exec

The webstore requires the "Add to Chrome" button to be there, but going directly to the link is the better way to access it.  Please try again and let me know if that does not resolve the issue.
