### ISSUE TITLE
Copying keeps stopping for more than 2 minutes

### ISSUE THREAD

**Issue by OctopusProteins** [ericyd/gdrive-copy#31]
### Are you requesting a feature or reporting a bug?
Error/Bug

### What is the current behavior?
Every time copying is paused because of Google quota limits, it doesn't automatically resume. I have to start it again from the app.

### What is the expected behavior?
The copy should automatically resume itself after 2 minutes,

### How would you reproduce the current behavior (if this is a bug)?
Start a copy, then wait for the Google quota limit.

### Specify your

* operating system: Windows 10 Creators
* browser: Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by hiNigel** [comment]
are you sure? In my case, copying resumes automatically after around 2 minutes.

**Comment by Aarbel** [comment]
I have same issue copying **folders with a lot of files**.

Here is a screen shot at the end of the google sheet "Copy folder log" :
![image](https://user-images.githubusercontent.com/25119847/33670935-88d6933e-daa6-11e7-8505-44e2181c1d4c.png)

(this message appears many times and the copy restarts, but at one time it definitely stops)

@ericyd how could we avoid this issue ? 

Thanks ! 

Clement

**Comment by ericyd** [comment]
It is a known issue and there is no solution at this time.

**Comment by Aarbel** [comment]
ok thanks

**Comment by ddibert** [comment]
Looks like a great tool here, but I'm running into this too!  I have thousands of files and it stops after a few hundred.  I am nowhere near my disk quota just under 1TB and I have 2TB.  Is there another quota being run into?   Like one of these...? https://developers.google.com/apps-script/guides/services/quotas

See my related posts:
https://productforums.google.com/forum/#!topic/drive/6XyRV2wl3iA;context-place=mydiscussions
https://productforums.google.com/forum/#!topic/apps/S8kIN7uyRGY;context-place=mydiscussions
https://productforums.google.com/forum/#!topic/drive/TGwKCS-Q5D8;context-place=mydiscussions
https://productforums.google.com/forum/#!topic/drive/xD7T6THuYzc;context-place=mydiscussions
https://productforums.google.com/forum/#!topic/drive/aGs3gCu0Iys;context-place=mydiscussions

Thanks!

**Comment by ericyd** [comment]
This should be fixed with v6.0.0. The solution is to sleep for 24 hours when the script has been running for 90 minutes. This avoids the daily google quota of 90 minutes per script.
