### ISSUE TITLE
Does the google drive copy folder application retain access to the folder id's in anyway ?

### ISSUE THREAD

**Issue by rh678** [ericyd/gdrive-copy#34]
### Are you requesting a feature or reporting a bug?

Enquiring

### Specify your

* operating system:
* browser:

**Comment by ericyd** [comment]
I'm not clear what the question is asking

**Comment by rh678** [comment]
Sorry for not being clear enough. When I access the copy folder add-on via spreadsheet, I noticed the spreadsheet stores the ids of the original folder and the copied folder. So I was wondering if this information is also stored anywhere else by the add-on or the application? This question is more related to how secure my data is, when I am using this add-on. Hope I am more clear now

**Comment by ericyd** [comment]
The app has no persistent storage and does not communicate with any services other than Google Drive. It doesn't store any data in any account other than the one you authorized to use the app. 

The app will create two files while copying. The first is the spreadsheet that tracks the progress of the copying. The other is only created if the app pauses during the copying. In this case, it will create a text document with relevant data that it can use to start where it left off. But, the document is created in your own Drive, not an external database.

I hope that helps.

**Comment by rh678** [comment]
Thanks a lot. this was very helpful and cleared my doubts

**Comment by ericyd** [comment]
also recently added a [privacy policy](https://github.com/ericyd/gdrive-copy/blob/master/PRIVACY_POLICY.md)
