### ISSUE TITLE
Copying of folder interrupted

### ISSUE THREAD

**Issue by AlexDings** [ericyd/gdrive-copy#37]
### Are you requesting a feature or reporting a bug?
Bug

### If reporting a bug, is there already an issue open for this same bug?
No

### What is the current behavior?
Error restarting script, trying again... |   |  
-- | -- | --
Empty JSON string | application (Copy Folder) | 824
Empty JSON string | application (Copy Folder) | 824
Empty JSON string | application (Copy Folder) | 824
Empty JSON string | application (Copy Folder) | 824
Empty JSON string | application (Copy Folder) | 824
Empty JSON string | application (Copy Folder) | 824

### What is the expected behavior?
To continue copying files

### How would you reproduce the current behavior (if this is a bug)?
No idea

### Specify your
* operating system: Chrome
* browser: Windows 10

**Comment by Zitruk** [comment]
Same here
![image](https://user-images.githubusercontent.com/15115680/35840615-90103dae-0ade-11e8-9cf9-e6b46342a47a.png)

**Comment by AlexDings** [comment]
I completely restarted the copying, so deleting progress made by this instance, and that run worked.

**Comment by ericyd** [comment]
Thanks for the update. I assume this falls into the "sporadic bug" category that will never be resolved due to the reliance on Google Apps Script and lack of reliable logging, but I'll leave this open in case it becomes more widespread.

**Comment by ericyd** [comment]
This should be fixed with v6.0.0.
