### ISSUE TITLE
Error: User rate limit exceeded. File: application (Copy Folder). Line: 506

### ISSUE THREAD

**Issue by shirshak55** [ericyd/gdrive-copy#46]
why is this error coming?

**Comment by ericyd** [comment]
It is due to exceeding the quota that is imposed on free scripts. I can't get around it unless I pay, but I really won't want to do that.

I should add a limited as suggested in this SO answer: https://stackoverflow.com/a/18743718

**Comment by bloggervista** [comment]
Yea it would be best bro

**Comment by ericyd** [comment]
I just added a request throttler to ensure that API requests are sent at a maximum of 10 per second, which should keep it below the rate limit. If this doesn't solve the issue, further investigation will take place in #6.

**Comment by xingfanxia** [comment]
> It is due to exceeding the quota that is imposed on free scripts. I can't get around it unless I pay, but I really don't want to do that.
> 
> I should add a limited as suggested in this SO answer: https://stackoverflow.com/a/18743718

Is there a way to use this script and pay for it? I need to transfer a few TB of videos in about a week. Thanks!

**Comment by shirshak55** [comment]
@xingfanxia transfering few tb is easy if u use service like multicloud.com :D

**Comment by shirshak55** [comment]
@xingfanxia or you can connect multiple gmail account and transfer it making it parallel :)

**Comment by ericyd** [comment]
This app/service will definitely not be a good fit for transferring a few tb in a week. You can definitely try but I almost guarantee it will not work.

**Comment by shirshak55** [comment]
@ericyd  have u tried. I have transferred like 2 tb in 2 day using that multi cloud tho.

**Comment by ericyd** [comment]
I have not tried, I don't have multiple tb of data to experiment with. Historically, the bugs reported for this app are due to people trying to copy enormous files/folders hence my recommendation to use another service.

Multicloud sounds like a great option, I have never used it myself but happy that you can vouch for it

**Comment by xingfanxia** [comment]
@ericyd @shirshak55  Thanks for the advice!

**Comment by xingfanxia** [comment]
@shirshak55 does multicloud work for the use case which I want to copy from a shared folder/drive?

**Comment by xingfanxia** [comment]
@shirshak55 I gave it a try, blocked by the 403 User limited exceeded :(
