### ISSUE TITLE
Allow copying to Team Drives

### ISSUE THREAD

**Issue by GerardBalaoro** [ericyd/gdrive-copy#47]
A remarkable feature for GSuite subscribers is the ability to create Team Drives, while this drive can be shared to other Gmail accounts, it does not support moving folders into it. I was hoping this tool will be able to create copies of a folder inside a Team Drive.

**Comment by ericyd** [comment]
Thank you for the comment, but going to close because it is a duplicate of [#10](https://github.com/ericyd/gdrive-copy/issues/10). It does seem like it would be a good feature to implement, just not sure when I'll have the time.
