### ISSUE TITLE
Unable to install - "Doesn't work with Google Apps Script"

### ISSUE THREAD

**Issue by NoSubstitute** [ericyd/gdrive-copy#48]
I'm wondering if I blocked something that is used used to install the app.
I tried using a different G Suite domain, and the app was installed just fine, no complaints.

Sadly, my error message is in Swedish. this little thing appears app the top of the browser window, and there is only an X-button for me to close it.
https://drive.google.com/file/d/1BrNuDpxfd3HNJBUJUm1WZp_hj9LjzeQz/view?usp=sharing
and after I click X, I get this.
https://drive.google.com/file/d/1qu3Hw9AsDLjMuLm2aTSWfGnc8CrX093E/view?usp=sharing

What could it be that I must allow, for the app to be allowed to be installed?
The Chrome extension itself I have allowed. Before that, I was immediately blocked from even trying to install.

**Comment by ericyd** [comment]
This app isn't really a Chrome extension even though it is listed as one in the Chrome Webstore.

Please just use the "Visit Website" button, that should take you straight to the app.

I would like to update this to either be a true Chrome extension or a true web app hosted somewhere else. I'll leave this open so maybe one day it can get there.

**Comment by NoSubstitute** [comment]
Thanks. But, no clue what I must allow so it can be installed?
One of my domains, the one with the error, is very locked down, and without proper error messages, it's hard to figure out what can be done to allow things we want.

**Comment by NoSubstitute** [comment]
I know how to bypass the block now.
I have to allow this URL in my _Chrome User Settings_ / _URL Blacklist/Whielist_.

https://accounts.google.com/signin/oauth?hd=MyGSFEDomainName&hl=sv&client_id=983475130545-e81q4d30k615fsr942krcejaajriv23a@developer.gserviceaccount.com

This is because I blacklist this URL, so I am in control over which Addons/Extensions people can install.
https://accounts.google.com/signin

So, this is no longer an issue for me personally.
