### ISSUE TITLE
Stops at 461

### ISSUE THREAD

**Issue by jeremiahlukus** [ericyd/gdrive-copy#53]
### Are you requesting a feature or reporting a bug?
Bug
### If reporting a bug, is there already an issue open for this same bug?
No
### What is the current behavior?
It stops on file 461
### What is the expected behavior?
Go through all the files and copy
### How would you reproduce the current behavior (if this is a bug)?
Have a folder that is over 461 files
### Specify your

* operating system:
* browser:

Mac OSX 10.13 
Chrome

**Comment by ericyd** [comment]
Can you let me know what type of file it keeps stopping on? I don't think it's specifically tied to being "number 461" but it might be tripping up on a certain file type.

**Comment by ericyd** [comment]
Rolling into #56 as it seems to be the same basic issue (script seems to be erroring out silently and not recovering)

**Comment by jeremiahlukus** [comment]
I will try again when I get home tomorrow. But I tried a few weeks ago and yes it was still happening.

**Comment by jeremiahlukus** [comment]
All files were jpegs I’m wanting to copy around 1200 high res photos.
