### ISSUE TITLE
Error: User rate limit exceeded....

### ISSUE THREAD

**Issue by OgnistyPoland** [ericyd/gdrive-copy#55]
### Are you requesting a feature or reporting a bug?
Bug
### If reporting a bug, is there already an issue open for this same bug?
No
### What is the current behavior?
...
### What is the expected behavior?
...
### How would you reproduce the current behavior (if this is a bug)?
Error: User rate limit exceeded. File: application (Copy Folder). Line: 513
### Specify your

* operating system: Windows 10 Home 1803
* browser: Microsoft Edge

**Comment by OgnistyPoland** [comment]
Nvm, this script has 750GB limit

**Comment by ericyd** [comment]
I just added a request throttler to ensure that API requests are sent at a maximum of 10 per second, which should keep it below the rate limit. If this doesn't solve the issue, further investigation will take place in #6.
