### ISSUE TITLE
Error, GoogleJsonResponseException: User rate limit exceeded

### ISSUE THREAD

**Issue by josephlu1996** [ericyd/gdrive-copy#6]
When the status of a file (in the copy log) is "Error, GoogleJsonResponseException: User rate limit exceeded," the file does not get copied.

**Comment by josephlu1996** [comment]
![image](https://cloud.githubusercontent.com/assets/24693545/21382527/0e0cfd40-c716-11e6-9ca4-9674caa06b33.png)

Files with status labeled "Error, GoogleJsonResponseException: User rate limit exceeded" do not get copied.

**Comment by josephlu1996** [comment]
![image](https://cloud.githubusercontent.com/assets/24693545/21382561/3642e69e-c716-11e6-83bc-c814eac2de35.png)
Files with status "Error, GoogleJsonResponseException: User rate limit exceeded" do not get copied.

**Comment by sPaCeMoNk3yIam** [comment]
I am also experiencing this error now every time. Usually if the folders hold very large files. Has Google changed the rate settings? Can you slow down the script? Copying manually seems to work.

**Comment by ericyd** [comment]
I would like to address this by adding all error files to a "retry" loop.  I've noted this in item 2 of https://github.com/ericyd/gdrive-copy/blob/master/README.md#project-maintenance.

**Comment by sPaCeMoNk3yIam** [comment]
thanks for the quick reply. problem is: once rate limit is exceeded you'd have to wait for 24 hours to get "unbanned". it would be better you rethink the script to spare requests. batch processing an delays. only 10 calls persecond are allowed afaik. and since this script may not be the only thing sending requests at a time, better limit to 1 per second or something...

**Comment by hklcf** [comment]
same here

![image](https://cloud.githubusercontent.com/assets/410302/22456131/8655bb5e-e7cb-11e6-878f-3c12ab81f203.png)

**Comment by fawzib** [comment]
make it sleep the moment we receive a quota error and keep retrying. skipping is never the solution.

@hklcf i believe your problem is related to character encoding. this is interesting for the author to look at.

**Comment by Mippy** [comment]
Got this error today while trying to copy folder with 210GB of files

**Comment by hklcf** [comment]
@Mippy copy 100GB per day

**Comment by ericyd** [comment]
I just added a request throttler to ensure that API requests are sent at a maximum of 10 per second, which should keep it below the rate limit. If this doesn't solve the issue, I'll re-open and continue investigation.
