### ISSUE TITLE
Files not copied after Error

### ISSUE THREAD

**Issue by Dev-Sapien** [ericyd/gdrive-copy#65]
### Are you requesting a feature or reporting a bug?
No

### If reporting a bug, is there already an issue open for this same bug?
No

### What is the current behavior?
Missing Files does not restore copying after the error occurred

### What is the expected behavior?
Recopy the missing file

### How would you reproduce the current behavior (if this is a bug)?
Automatic

### Specify your
Error: Internal Error. File: application (Copy Folder). Line: 546
Error: User rate limit exceeded. File: application (Copy Folder). Line: 546

* operating system:  Windows 10
* browser: Chrome Version 71.0.3578.98

**Comment by ericyd** [comment]
Hmm, this is the same underlying issue as #55 and #62, which I thought I fixed (clearly not).

It would be nice to add "retry" functionality, but its not quite so simple because the number of retries per file would need to be tracked and verify that we don't exceed a given maximum. Otherwise, files that are legitimately broken would result in an infinite loop. As you may have seen, progress on this project has been extremely slow lately, so I'll cross my fingers for a PR from an angel.

**Comment by maldjulio** [comment]
![capture](https://user-images.githubusercontent.com/46313299/50584197-e844a300-0e22-11e9-8964-b18a931cb5be.PNG)

Same thing here. Great program though! Most of my files were copied over; I had to do some manual copies. Will be sending some bitcoin once I get some in my account. Thank you.

**Comment by Dev-Sapien** [comment]
> Hmm, this is the same underlying issue as #55 and #62, which I thought I fixed (clearly not).
> 
> It would be nice to add "retry" functionality, but its not quite so simple because the number of retries per file would need to be tracked and verify that we don't exceed a given maximum. Otherwise, files that are legitimately broken would result in an infinite loop. As you may have seen, progress on this project has been extremely slow lately, so I'll cross my fingers for a PR from an angel.

A retry functionality can be run once, and a button can be added to the sheet to run the retry script for manual retry

**Comment by OgnistyPoland** [comment]
Yes, retry button would be great

**Comment by ericyd** [comment]
I decided to handle retries internally for now, as adding a "retry" button would require some sort of persistent storage for those errors, outside of the properties document I'm already using. If this doesn't prove adequate I will consider other solutions. 

This update was just pushed live, and should be deployed to users within an hour or so.

**Comment by OgnistyPoland** [comment]
@ericyd I dont see retry button, can you show me where its hidden?

**Comment by ericyd** [comment]
I didn't add a retry button, the script just automatically retries error files. It tries 3 times before finally logging the error. If you're still seeing errors, please feel free to browse the other open issues or open a new one

**Comment by OgnistyPoland** [comment]
I got Error: User rate limit exceeded. File: application (Copy Folder). Line: 366 and I tried to Retry with a button, but now I know that we don't have a button
