### ISSUE TITLE
Not copying entire folder

### ISSUE THREAD

**Issue by sofawall** [ericyd/gdrive-copy#69]
### Are you requesting a feature or reporting a bug?
Reporting a bug
### If reporting a bug, is there already an issue open for this same bug?
No
### What is the current behavior?
It does not copy all the files in a folder
### What is the expected behavior?
It would copy all the files in a folder
### How would you reproduce the current behavior (if this is a bug)?
Try to copy a specific drive, wait for it to finish. Verify not all files copied over.
### Specify your

* operating system: Windows 10 Pro
* browser: Google Chrome

**Comment by ericyd** [comment]
This sounds like a duplicate of #67
