### ISSUE TITLE
Unable to install application due to conflict with another extension

### ISSUE THREAD

**Issue by tmalaher** [ericyd/gdrive-copy#7]
When I try to install Copy Folder or Transfer Ownership Apps I get a message about being unable to install the application because it conflicts with "Google Apps Script".
After reading this: <https://groups.google.com/a/chromium.org/forum/#!topic/chromium-apps/chSmO47guyI>

I was able to find this in my Extensions directory, in a file called:

`.../eoieeedlomnegifmaghhjnghhmcldobl/1.5_0/manifest.json`

   `"web_url": "https://script.google.com/start"`

This extension has a name of Google Apps Script and a description of "Create and edit scripts".
Chrome store page: <https://chrome.google.com/webstore/detail/google-apps-script/eoieeedlomnegifmaghhjnghhmcldobl?utm_source=chrome-app-launcher-info-dialog>

Maybe there is something you could tweak in your manifest to stop the conflict?

In any case the workaround of just using the "Visit Website" link from the store to kick off the application works fine, even if it is a little inconvenient.

**Comment by ericyd** [comment]
I have not created a manifest for this project and I do not plan to. This app is built with Google Apps Script and deployed as a web app through the Google Apps Script interface.  

The documentation for deploying apps in the Chrome Web Store indicates that the manifest should be included with packaged apps, and it is uploaded with the script when publishing to the Chrome Web Store.  However, my understanding is that the deployment is a little different for hosted web apps.  Per the documentation for [deploying a web app](https://developers.google.com/apps-script/guides/distribute-web-app):

> Do not upload a file in the Upload section at the top of the page; Apps Script generates this file automatically for you and uploading a separate file will cause the publication to fail.

I do not know any other way to update the manifest file except for uploading it in this way, which the documentation recommends against.  If this changes in the future I can re-open this issue, but for now it will be closed.

If there is better documentation for how to integrate an application built with Google Apps Script into the Chrome Web Store or Google Drive, please feel free to post them or send me an email.
