### ISSUE TITLE
Error: File not found: . File: application (CopyFilesDrive). Line: 326

### ISSUE THREAD

**Issue by vaccarieli** [ericyd/gdrive-copy#78]
### Are you requesting a feature or reporting a bug?
Reporting a Bug

### If reporting a bug, is there already an issue open for this same bug?
Dont know, there was nothing related exactly to what Im experiencing.

### What is the current behavior?

I am using the current app deployed in my own school drive account to avoid a little less issues related to quota, the thing is that I have copied so many folders in alphabetic order and they were all successfully copied, SO the folder that I am having issues with has 383 files, so when it comes to folder with more than 90 files the copy everything starts to copy and then comes the message ``Paused due to Google quota limits - copy will resume in 1-2 minutes`` after 1 or 2 minutes it will start again it will copy 4 or 5 more files and bam !! comes the error ``Error: File not found: . File: application (CopyFilesDrive). Line: 326" ``  

AND always happen at exactly 102 files!! 
``Error: File not found: . File: application (CopyFilesDrive). Line: 326"
I have tried to Resume but will take only one more file copy it and then !!
``Error: File not found: . File: application (CopyFilesDrive). Line: 326"

### What is the possible solution you can come up with?

I think that if we pause the the copying process more than 2 minutes lets say 4 minutes, and see what it says, because it is probably and error with google drive itself not the copy folder app.

* operating system:

Windows 10 Pro

* browser:

Google Chrome
Mozilla FireFox
Microsoft Edge

**Comment by ericyd** [comment]
Thanks for the bug report. Just pushed a change for this, it takes up to an hour to propagate to all users. I mistakenly introduced this in January due to some bad refactoring.
