### ISSUE TITLE
Error: Unable to find a folder with the supplied URL (using app built from source)

### ISSUE THREAD

**Issue by sbwoodside** [ericyd/gdrive-copy#92]
### Are you requesting a feature or reporting a bug?

Bug

### If reporting a bug, is there already an issue open for this same bug?

No

### What is the current behavior?

When pasting in a folder URL, I get the error:

> Error: Unable to find a folder with the supplied URL. You submitted https://drive.google.com/drive/folders/XYZ. Please verify that you are using a valid folder URL and try again.

<img width="1110" alt="screen shot 2019-03-06 at 14 48 42" src="https://user-images.githubusercontent.com/47834/53921501-a3b1cf80-403e-11e9-8446-e52d33f850e5.png">

### What is the expected behavior?

It would accept the folder URL.

### How would you reproduce the current behavior (if this is a bug)?

1. Build the app with `clasp` using the new instructions in https://github.com/ericyd/gdrive-copy/pull/90
2. Open the app using the web app URL and authorize it
3. Open a folder in my google drive in the same web browser
4. Copy the URL in the address bar (I also tried using the "Sharing link")
5. Paste it into the app.

### Specify your

* operating system: MacOS 10.14.3 (18D109)
* browser: Chrome Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by ericyd** [comment]
This is covered by a test, I'd be very surprised if this was a bug in the code. I haven't finalized that clasp PR so its more likely a bug in the build process. I'll have to take a look at home

relevant test: https://github.com/ericyd/gdrive-copy/blob/master/test/parseURL.test.js

The other possibility is being logged into multiple accounts. The auth logic here is poor, you can see a long history of issues about it. If you have multiple accounts and are logged in on both, its highly likely that its trying to find a folder owned by the wrong account and therefore failing because you don't have permission to view

**Comment by sbwoodside** [comment]
Using the built version of the app that I already have, I have tried logging out of all my multiple accounts and then logging in with the single account and still get the same result. I have also tried using Chrome.

Here is what I see in Stackdriver:

```2019-03-20 16:25:34.953 EDT
Error: Unable to find a folder with the supplied URL. You submitted https://drive.google.com/drive/folders/XXX. Please verify that you are using a valid folder URL and try again. at getMetadata(public:113)
  
Expand all | Collapse all {
 insertId:  "-eoxy70d1umo"   
 jsonPayload: {
  context: {
   reportLocation: {
    filePath:  "public"      
    functionName:  "getMetadata"      
    lineNumber:  113      
   }
  }
  message:  "Error: Unable to find a folder with the supplied URL. You submitted https://drive.google.com/drive/folders/XXX. Please verify that you are using a valid folder URL and try again.
    at getMetadata(public:113)
"    
  serviceContext: {
   service:  "AKfycbwnoJPpzQvCZzweilktukDtxJgASeUutATASsm0LISD"     
  }
 }
 labels: {
  script.googleapis.com/deployment_id:  "AKfycbwnoJPpzQvCZzweilktukDtxJgASeUutATASsm0LISD"    
  script.googleapis.com/process_id:  "EAEA1GOy41QcKKVIN3KsxipGLVO0Gkcx50Y350Jck68PCJu-hPx_JBkb6gnN_fla1iB2PoH1CqEf6ZFkM4ZhftKQ_ClQy6pFryhLXrzPBrnR4sLfSXXyCdrQiPUmlhhp7B_IH9Xelw8XSC2t57dGutCSeSxbhFxPTgypxsg"    
  script.googleapis.com/project_key:  "MaDjLHP1D29RwfMX5OFf583FRbbDWcX2d"    
  script.googleapis.com/user_key:  "AMkai8mLPvJ5L4EgtudJ+frTK0GQjQmFmJO4SFL64mAsFRE28kfe9ZmYyjLJzCZ0OYtKxLYPKoJ4"    
 }
 logName:  "projects/project-id-2479270600962067600/logs/script.googleapis.com%2Fconsole_logs"   
 receiveTimestamp:  "2019-03-20T20:25:35.964119941Z"   
 resource: {
  labels: {
   function_name:  "getMetadata"     
   invocation_type:  "web app"     
   project_id:  "project-id-2479270600962067600"     
  }
  type:  "app_script_function"    
 }
 severity:  "ERROR"   
 timestamp:  "2019-03-20T20:25:34.953Z"   
}
```

**Comment by ericyd** [comment]
Trying to identify if this is a code issue (incorrectly parsing the URL to get the ID) or a permissions issue with the folder you're trying to copy.

Could you please
1. log is as the account in question
2. paste the folder URL into the app, verify response
3. use this page with the same session to check the folder ID: https://developers.google.com/drive/api/v2/reference/files/get#try-it

If step 2 fails but step 3 works, could you please copy/paste the exact URL you're using here. You can substitute the ID for XXX or any other placeholder, but the full URL will be helpful. If it is literally `https://drive.google.com/drive/folders/:ID` then I really can't wrap my head around what the issue would be, but I'll continue investigating when I get back to working on that `clasp` PR

**Comment by sbwoodside** [comment]
Thanks. The test folder ID is https://drive.google.com/drive/folders/13_mdqjoE688Swaask9XYhHGEqD6Ncc6J I think that's safe to share.

Step 3, I entered that URL into `fileId` and I got this error:

```{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notFound",
    "message": "File not found: https://drive.google.com/drive/folders/13_mdqjoE688Swaask9XYhHGEqD6Ncc6J",
    "locationType": "other",
    "location": "file"
   }
  ],
  "code": 404,
  "message": "File not found: https://drive.google.com/drive/folders/13_mdqjoE688Swaask9XYhHGEqD6Ncc6J"
 }
}
```

Here is a screen shot to show that it does actually exist, and it's owned by me, and I'm only logged into one account:

<img width="1194" alt="Screen Shot 2019-03-27 at 00 38 15" src="https://user-images.githubusercontent.com/47834/55050744-ab0a3e80-5028-11e9-81bf-eae0c6d5059a.png">

**Comment by ericyd** [comment]
What happens if you just put `13_mdqjoE688Swaask9XYhHGEqD6Ncc6J` into the `fileId` field of the Google Drive API tester?

**Comment by sbwoodside** [comment]
It works! 👍 Specifically Google Drive API tester works with just `13_mdqjoE688Swaask9XYhHGEqD6Ncc6J` but not with the full URL.

Now this is interesting. Just for the heck of it I went through `Deploy as web app` again and it started working. I've tried changing `Execute the app as` and `Who has access to the app` and it works with any combinations now. I'm wondering if either the initial deployment created by `clasp` didn't work, or if google fixed a bug, or what.

<img width="445" alt="Screen Shot 2019-04-02 at 00 19 29" src="https://user-images.githubusercontent.com/47834/55376203-60336f80-54dd-11e9-9467-d0bb725987c3.png">

So I'm able to copy now within my own Drive. However my ultimate goal is to copy into a Team Drive. When I set the destination folder to be the Team Drive or a folder inside a Team Drive I get `Error: Unable to find a folder with the supplied URL. ` for that destination. The Google Drive API tester also errors out on both the ID alone and also the full URL. Should I open a new ticket for this issue? Or I could follow up with Google.

As a workaround, I think that I can make a copy into my own drive, which makes me the owner of everything, and then use the Drive UI to copy it subsequently into the Team Drive.

**Comment by ericyd** [comment]
I'm glad to hear it is mostly working. There is a long standing open issue to add Team Drives support (#10) so I would prefer any additional conversation happen there.

**Comment by sbwoodside** [comment]
No problem. Thanks for all of your help!

**Comment by wiktor-cobry** [comment]
Note for anyone else that is going through this bug - this error throws if your Advanced Drive API isn't switched on.

@sbwoodside may have fixed this issue by switching it on through script.google.com > Advanced Services, but the best practice is to add this to the manifest file before building and pushing your code:

```
  "dependencies": {
    "enabledAdvancedServices": [{
      "userSymbol": "Drive",
      "serviceId": "drive",
      "version": "v2"
    }]
  },
```
