### ISSUE TITLE
FTP FEATURE

### ISSUE THREAD

**Issue by vaccarieli** [ericyd/gdrive-copy#93]
### Are you requesting a feature or reporting a bug?

FEATURE

### WHAT KIND OF FEATURE?

FEATURE TO MAKE GOOGLE DRIVE ACCOUNT AN FTP SERVER, SO WE CAN ACCESS ANY FILE IN ANY PLACE BY USING ANY FOLDER BROWSER, I WOULD LIKE TO ACCESS SOME MOVIES IN MY PHONE BY BEING ABLE TO USE GOOGLE DRIVE FTP SERVER AND CONNECT TO IT.

**Comment by ericyd** [comment]
I do not have any ability to implement something like this, I do not work for Google
