### ISSUE TITLE
Can this code to be implemented to my own domain as a new instance?

### ISSUE THREAD

**Issue by RePaaja** [ericyd/gdrive-copy#94]
### Specify your

* operating system:
* browser:

**Comment by ericyd** [comment]
This is answered in the faq within the application, but the answer is yes

**Comment by ericyd** [comment]
My apologies, not answered in the FAQ but there is an entire doc dedicated to this in the repo

https://github.com/ericyd/gdrive-copy/blob/master/howto_for_non-developers.md

**Comment by RePaaja** [comment]
Thank you,



I will continue with your instructions, test and see how to proceed.



Over time I need additional code to implement processes above Drive/G Suite
– something more than workflow.



*Are you doing this kind development? And what are your terms here?*



Or do you have this kind of solution already available?



Br Repa



Reijo Paajanen

CEO                                         Prinnox Oy

+358 50 1905                        Melkonkatu 9 A 31

reijo.paajanen@prinnox.fi 00210 Helsinki











*Lähettäjä:* Eric Yancey Dauenhauer <notifications@github.com>
*Lähetetty:* Saturday, 16 March, 2019 21:16
*Vastaanottaja:* ericyd/gdrive-copy <gdrive-copy@noreply.github.com>
*Kopio:* RePaaja <reijo.paajanen@prinnox.fi>; Author <
author@noreply.github.com>
*Aihe:* Re: [ericyd/gdrive-copy] Can this code to be implemented to my own
domain as a new instance? (#94)



My apologies, not answered in the FAQ but there is an entire doc dedicated
to this in the repo

https://github.com/ericyd/gdrive-copy/blob/master/howto_for_non-developers.md

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ericyd/gdrive-copy/issues/94#issuecomment-473576435>,
or mute the thread

**Comment by ericyd** [comment]
I'm not taking on new projects at this time

**Comment by RePaaja** [comment]
Eric,



My expert has been trying to implement the code for some time according to
your instructions.



However we are getting error message: TypeError: Odotettiin tyyppiobjektin
argumenttia, mutta sen sijaan saatiin tyyppi undefined. (line 3, file
"application", project "gdrive-copy")

Translation is ~: TypeError: Expected argument of type object but instead
got type undefined. (line 3, file "application", project "gdrive-copy")



This is the testing link:

https://script.google.com/a/macros/prinnox.fi/s/AKfycbx2mOPCvShOv1XHYWPoY0DCbXrZBP_C93-SBx4cXtbeLTz7odI/exec



Any advice now?



Br Reijo



Reijo Paajanen

CEO                                         Prinnox Oy

+358 50 1905                        Melkonkatu 9 A 31

reijo.paajanen@prinnox.fi 00210 Helsinki







*Lähettäjä:* Eric Yancey Dauenhauer <notifications@github.com>
*Lähetetty:* Saturday, 16 March, 2019 21:16
*Vastaanottaja:* ericyd/gdrive-copy <gdrive-copy@noreply.github.com>
*Kopio:* RePaaja <reijo.paajanen@prinnox.fi>; Author <
author@noreply.github.com>
*Aihe:* Re: [ericyd/gdrive-copy] Can this code to be implemented to my own
domain as a new instance? (#94)



My apologies, not answered in the FAQ but there is an entire doc dedicated
to this in the repo

https://github.com/ericyd/gdrive-copy/blob/master/howto_for_non-developers.md

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ericyd/gdrive-copy/issues/94#issuecomment-473576435>,
or mute the thread

**Comment by ericyd** [comment]
I don't know the cause of that error. I would recommend copying and pasting the files from the `dist` folder into Google apps script. I hope that helps. I'm sorry I haven't had any time for this project recently
