### ISSUE TITLE
Copy folder creating multiple duplicate sheets in the new folder

### ISSUE THREAD

**Issue by QASICross** [ericyd/gdrive-copy#95]
### Specify your

* operating system:
* browser:

**Comment by QASICross** [comment]
I'm copying a folder that has 38 spreadsheets in it.  When I go to the new folder that I copied to there are 10 duplicate sheets for each sheet I copied.  And it is taking so long to copy all of these duplicates that it times out and doesn't finish copying all of them.  Then sends me many, many e-mail notifications that it timed out and couldn't finish copying.

**Comment by ericyd** [comment]
Sounds like the same issue occurring in #96. Not sure why this would have happened but I added an extra check to avoid reprocessing duplicate IDs.

**Comment by QASICross** [comment]
Thank you so much.  I'll try it again and let you know how it goes.  :-)

**Comment by QASICross** [comment]
Hi Eric,
It is still making multiple copies of files inside the folder.  I'm
attaching a print screen of what is happening.  There should be only one of
each name in this file and there are 5.
Thanks,
Cindy

**Comment by ericyd** [comment]
Hmm, not sure what would be causing this but I rolled back to 2 versions ago, since I've been hearing this report from a few other people. Hopefully that fixes the issue.
