### ISSUE TITLE
Tried ending the script...

### ISSUE THREAD

**Issue by rojwagner** [ericyd/gdrive-copy#96]
While copying a folder it got caught in a loop. Everything went over, so I tried just deleting the script file in the folder. Now I am receiving the following e-mail from google about every 15 minutes:

Your script, Copy Folder, has recently failed to finish successfully. A summary of the failure(s) is shown below. To configure the triggers for this script, or change your setting for receiving future failure notifications, click here.

Start	Function	Error Message	Trigger	End
3/14/19 4:33 PM	copy	Exceeded maximum execution time	time-based	3/14/19 4:39 PM
Sincerely,

Google Apps Script

Need help? Visit the Google Apps Script documentation. Please do not reply to this message. (c) 2019 Google

**Comment by ericyd** [comment]
Not sure why this would be happening but I added an extra check to avoid re-processing duplicate IDs.

The emails get quite delayed from google apps script. But they will stop now that you've deleted the folder. Sorry for the hassle.
